// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxCzGDLlUS475skr-ydkdZjeh_x1ZZ_Q8',
    appId: '1:142326281544:web:81107840fa73609a126f7d',
    messagingSenderId: '142326281544',
    projectId: 'giftstor-86217',
    authDomain: 'giftstor-86217.firebaseapp.com',
    storageBucket: 'giftstor-86217.firebasestorage.app',
    measurementId: 'G-ZP68BHJZ64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmmcHEI2-pRK5aeMbpIIYPO-Ibh5iAcTM',
    appId: '1:142326281544:android:ed47b419bb9fcd98126f7d',
    messagingSenderId: '142326281544',
    projectId: 'giftstor-86217',
    storageBucket: 'giftstor-86217.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1q9HYk_z0_uemi8NpdpjROn7ypErpcPI',
    appId: '1:142326281544:ios:856ecd2a8b936967126f7d',
    messagingSenderId: '142326281544',
    projectId: 'giftstor-86217',
    storageBucket: 'giftstor-86217.firebasestorage.app',
    iosBundleId: 'com.example.giftstoreFlutter',
  );
}
